version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "all"
    open-pull-requests-limit: 10
